// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgW4UrTeJFUAfrBlkrnxiynkB7auShZ8',
    appId: '1:12842599823:web:f2381831b46f03be13b7fa',
    messagingSenderId: '12842599823',
    projectId: 'khadmatdz-6d358',
    authDomain: 'khadmatdz-6d358.firebaseapp.com',
    storageBucket: 'khadmatdz-6d358.appspot.com',
    measurementId: 'G-3YW4N860YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9CKtTS6Uy-KVLbD5arBgkp4ii1DuaK_0',
    appId: '1:12842599823:android:d6eb81742370ec2813b7fa',
    messagingSenderId: '12842599823',
    projectId: 'khadmatdz-6d358',
    storageBucket: 'khadmatdz-6d358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTmrR4eA0UgWvaxRvqsMJ-vuIQPqLhgas',
    appId: '1:12842599823:ios:023c8c4c2ee4c2d513b7fa',
    messagingSenderId: '12842599823',
    projectId: 'khadmatdz-6d358',
    storageBucket: 'khadmatdz-6d358.appspot.com',
    androidClientId: '12842599823-t2agkci7l99la04ebdndp7ah12u4s8qf.apps.googleusercontent.com',
    iosClientId: '12842599823-ifo23brojd5ke26ki3ku48q6ul6gr0v5.apps.googleusercontent.com',
    iosBundleId: 'khadmatdz.com.khadmatdz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTmrR4eA0UgWvaxRvqsMJ-vuIQPqLhgas',
    appId: '1:12842599823:ios:170e7f22ae8b36a713b7fa',
    messagingSenderId: '12842599823',
    projectId: 'khadmatdz-6d358',
    storageBucket: 'khadmatdz-6d358.appspot.com',
    androidClientId: '12842599823-t2agkci7l99la04ebdndp7ah12u4s8qf.apps.googleusercontent.com',
    iosClientId: '12842599823-jgt8dr4mcog7pch5pv3umjgm7ta64oj8.apps.googleusercontent.com',
    iosBundleId: 'khadmatdz.com.khadmatdz.RunnerTests',
  );
}
